// <auto-generated />
namespace My.EntityFrameWork.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Initialsetup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initialsetup));
        
        string IMigrationMetadata.Id
        {
            get { return "201703031823374_Initial setup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
